import { Application } from 'express';
import articleSubmittedForWaitReview from './articleSubmittedForWaitReview/articleSubmittedForWaitReview';
import articleSubmittedForDraft from './articleSubmittedForDraft/articleSubmittedForDraft';
import articleSubmittedForReview from './articleSubmittedForReview/articleSubmittedForReview';
import articleSubmittedForReject from './articleSubmittedForReject/articleSubmittedForReject';
import articleSubmittedForTakeback from './articleSubmittedForTakeback/articleSubmittedForTakeback';
import articleSubmittedForDelete from './articleSubmittedForDelete/articleSubmittedForDelete';
import articleForSearchAll from './articleForSearchAll/articleForSearchAll';
import articleForSearchByUserID from './articleForSearchByUserID/articleForSearchByUserID';
import articleForSearchByArticleTreeId from './articleForSearchByArticleTreeId/articleForSearchByArticleTreeId';
import articleForSearchByArticleId from './articleForSearchByArticleId/articleForSearchByArticleId';
import articleSubmittedForEdit from './articleSubmittedForEdit/articleSubmittedForEdit';
import articleStatusForSearchAll from './articleStatusForSearchAll/articleStatusForSearchAll';
import articleSubmittedForDraftTurnWaitReview from './articleSubmittedForDraftTurnWaitReview/articleSubmittedForDraftTurnWaitReview';
import articleTagsBatchUpdate from './articleTagsBatchUpdate/articleTagsBatchUpdate';

export default ({ app, jwtKey }: { app: Application; jwtKey: string }) => {
	articleSubmittedForDraft({ app, jwtKey });
	articleSubmittedForWaitReview({ app, jwtKey });
	articleSubmittedForReview({ app, jwtKey });
	articleSubmittedForReject({ app, jwtKey });
	articleSubmittedForTakeback({ app, jwtKey });
	articleSubmittedForDelete({ app, jwtKey });
	articleForSearchAll({ app, jwtKey });
	articleForSearchByUserID({ app });
	articleForSearchByArticleTreeId({ app });
	articleForSearchByArticleId({ app, jwtKey });
	articleSubmittedForEdit({ app });
	articleStatusForSearchAll({ app });
	articleSubmittedForDraftTurnWaitReview({ app, jwtKey });
	articleTagsBatchUpdate({ app });
};
