import { Application } from 'express';
import articleSubmittedForWaitReview from './articleSubmittedForWaitReview';
import articleSubmittedForDraft from './articleSubmittedForDraft';
import articleSubmittedForReview from './articleSubmittedForReview';
import articleSubmittedForReject from './articleSubmittedForReject';
import articleSubmittedForTakeback from './articleSubmittedForTakeback';
import articleSubmittedForDelete from './articleSubmittedForDelete';
import articleForSearchAll from './articleForSearchAll';
import articleForSearchByUserID from './articleForSearchByUserID';
import articleForSearchByArticleTreeId from './articleForSearchByArticleTreeId';
import articleForSearchByArticleId from './articleForSearchByArticleId';
import articleSubmittedForEdit from './articleSubmittedForEdit';
import articleStatusForSearchAll from './articleStatusForSearchAll';
import articleSubmittedForDraftTurnWaitReview from './articleSubmittedForDraftTurnWaitReview';

export default ({ app, jwtKey }: { app: Application; jwtKey: string }) => {
	articleSubmittedForDraft({ app, jwtKey });
	articleSubmittedForWaitReview({ app, jwtKey });
	articleSubmittedForReview({ app, jwtKey });
	articleSubmittedForReject({ app, jwtKey });
	articleSubmittedForTakeback({ app, jwtKey });
	articleSubmittedForDelete({ app, jwtKey });
	articleForSearchAll({ app, jwtKey });
	articleForSearchByUserID({ app });
	articleForSearchByArticleTreeId({ app });
	articleForSearchByArticleId({ app, jwtKey });
	articleSubmittedForEdit({ app });
	articleStatusForSearchAll({ app });
	articleSubmittedForDraftTurnWaitReview({ app, jwtKey });
};
